### ISSUE TITLE
CPFP doesn't work for me

### ISSUE THREAD

**Issue by agustinpfs** [nbd-wtf/obw#18]
When I tap "Boost", after choosing the fee, the following message appears: "A transaction could not be transmitted, please make sure the wallet has a network connection and try again" But my phone is connected to the network.

**Comment by Gravity2106** [comment]
You mean CPFP or RBF?
your wallet shows "offline" or "chain" on the right top of the screen?

**Comment by fiatjaf** [comment]
This may be because the wallet is not connected to any Electrum server or could be because there is an inconsistency in your UTXO data and the wallet may be building an invalid transaction because of that.

What version of the wallet are you using?
Are you connecting to a custom Electrum server?
Does it show the "offline" tag at the top of the home screen?

**Comment by agustinpfs** [comment]
> This may be because the wallet is not connected to any Electrum server or could be because there is an inconsistency in your UTXO data and the wallet may be building an invalid transaction because of that.
> 
> What version of the wallet are you using? Are you connecting to a custom Electrum server? Does it show the "offline" tag at the top of the home screen?


What version of the wallet are you using? The last, v0.1.8
Are you connecting to a custom Electrum server? No, I'm using random nodes
Does it show the "offline" tag at the top of the home screen? No, the wallet was online

**Comment by agustinpfs** [comment]
I reinstalled and solved it. Thank you for your answers
