### ISSUE TITLE
After latest update 0.1.8, it stays offline with custom server

### ISSUE THREAD

**Issue by ElucGeek** [nbd-wtf/obw#21]
I just did the update from 0.1.5 to 0.1.8 (missed some releases). And now it's always offline, impossible to use it. I tried to downgrade to a previous version but it's always saying that I'm in 0.1.8-9, is there a mechanism that prevent the downgrade?

**Comment by fiatjaf** [comment]
Yes, this happens because your self-hosted Electrum server is using a self-signed certificate, which is (supposedly?) insecure and 0.1.8 enforces that you must have a valid certificate.

I guess I'll have to rework that for the next release, but I am not sure what to do about it exactly.

In the meantime, you can connect to a plaintext Electrum server if you serve it from the default TCP-not-SSL port 50001 and specify that on OBW settings.

**Comment by fiatjaf** [comment]
Also beware that version 0.1.5 had some syncing bugs so if you had a wallet of lots of old UTXOs there is a big chance your wallet currently has a broken view of its own state and you should wipe it out and restore from seed (unless you have normal lightning channels).

**Comment by ElucGeek** [comment]
My Electrs is not with self-signed certificate, it's a bit more complicated. I have an URL pointing to a server which have a valid Let's Encrypt certificate, then the server is doing reverse-proxy to a second machine on the same local network where is Electrs and here there is no SSL. So far and with other wallet it was not a problem. From OBW point of view it should be transparent with a valid certificate. In the meantime I switch back to Tor connection until I find a solution.
