### ISSUE TITLE
Paying to a lightning address fails when base64 encoded image data length is over 136536 bytes

### ISSUE THREAD

**Issue by Bashy** [nbd-wtf/obw#5]
When paying to a lightning address, if `metadata` object contains a `image/jpeg;base64` or `image/png;base64` value length over 136,536 bytes, a Java exception is raised.

![Screenshot_20221023-010649_OBW](https://user-images.githubusercontent.com/540518/197365871-5eb722f9-d5c4-448a-8ea7-1e3c3e4e4a0e.jpg)

**Comment by fiatjaf** [comment]
That is according to the spec, see https://github.com/fiatjaf/lnurl-rfc/blob/luds/06.md#wallet-to-service-interaction-flow


Here's a screenshot because it is hard to find:

![2022-10-22-202807_805x755_scrot](https://user-images.githubusercontent.com/1653275/197366056-f6851b54-5764-4cdf-93a0-a7641547f458.png)
